
const manhwass = [
    "Reverse Villain",
    "Solo Leveling",
    "I Shall Live as a Prince",
    "The Horizon",
    "The Boxer",
    "3CM Hunter",
    "Again My Life",
    "Reincarnated War God",
    "Yongbi",
    "Gosu",
    "The Breaker",
    "The Breaker: New Waves",
    "MookHyang - The Origin",
    "Mujang",
    "Red Storm",
    "The Sword of Glory",
    "Bastard",
    "Sweet Home",
    "Pigpen",
    "Leviathan",
    "Hardcore Leveling Warrior",
    "Efforts Never Betray",
    "Terror Man",
    "Her Summon",
    "Asura",
    "Dark Mortal",
    "I Will Die Soon",
    "Dreamcide",
    "The Greatest Outcast",
    "Distant Sky",
    "I am the Sorcerer King",
    "Medical Return",
    "Revival Man",
    "Second Life of a Gangster",
    "Rooftop Swordmaster",
    "Warble",
    "Epic of Gilgamesh",
    "Girls of the Wild's",
    "Miracle Hero!",
    "My Life as a Loser",
    "Mosquito War",
    "Noblesse",
    "The Promised Orchid",
    "Immortal Regis",
    "Cavalier of the Abyss",
    "Crimson Karma",
    "I Stack Experience Through Reading Books",
    "Nano List",
    "Planetary Human",
    "Shin Angyo Onshi",
    "DICE: The Cube That Changes Everything",
    "Samadhi",
    "Delivery Knight",
    "Flow",
    "Slave B",
    "Trinity Wonder",
    "Unholy Blood",
    "Hive",
    "Auto Hunting",
    "Heavenly Demon Bakery",
    "Michelin Star",
    "Kitchen Soldier",
    "The Chef Hides His Blessing",
    "Street Restaurant of a Returned Hero",
    "Please Have a Meal",
    "Youngest Chef from the 3rd Rate Hotel",
    "Leveling Up, By Only Eating!",
    "God of Cooking",
    "Return of the SSS-Class Ranker",
    "The Novel's Extra (Remake)",
    "Superhuman Battlefield",
    "Magical Shooting: Sniper of Steel",
    "Kill The Dragon",
    "+99 Wooden Stick",
    "Barbarian Quest",
    "My Daughter is the Final Boss",
    "Worthless Regression",
    "Return of the Unrivaled Spear Knight",
    "Storm Inn",
    "Chronicles of Heavenly Demon",
    "The Story of a Low-Rank Soldier Becoming a Monarch",
    "Murim Login",
    "The Tutorial Tower of the Advanced Player",
    "Arcane Sniper",
    "Starting Today, I'm a Player",
    "Seoul Station Druid",
    "Bowblade Spirit",
    "The Second Coming of Gluttony",
    "I Stole the Number One Ranker's Soul",
    "Auto Hunting with my Clones",
    "Genius of the Unique Lineage",
    "Cursed Manager’s Regression",
    "Player Who Returned 10,000 Years Later",
    "A Gate Opened on my First Day as a Politician",
    "Clever Cleaning Life of the Returned Genius Hunter",
    "Transcension Academy",
    "Carnivorous Hunter",
    "The Reincarnation of the Forbidden Archmage",
    "The Novel's Extra (Remake)",
    "The Newbie is Too Strong",
    "I Obtained a Mythic Item",
    "Superhuman Battlefield",
    "Is this Hunter for Real?",
    "I Have an SSS-rank Trait, But I want a Normal Life",
    "My Daughter is the Final Boss",
    "The Hero Returns",
    "Street Restaurant of a Returned Hero",
    "Leveling Up with Likes",
    "The World after the Fall",
    "Return of the Disaster-Class Hero",
    "Leveling with the Gods",
    "Limit Breaker",
    "Spirit Farmer",
    "Dungeon Hunters are Bastards",
    "990k Ex-Life Hunter",
    "Dungeon House",
    "Hoarding in Hell",
    "Seoul Station Druid",
    "Max Level Returner",
    "SSS-Class Gacha Hunter",
    "The S-Classes that I Raised",
    "Maxed Out Leveling",
    "The Tutorial Tower of the Advanced Player",
    "Return to Player",
    "Second Life Ranker",
    "Solo Necromancy",
    "Murim Login",
    "My Dad is Too Strong",
    "Kill the Hero",
    "Solo Max-Level Newbie",
    "Seoul Station Necromancer",
    "Return of the Shattered Constellation",
    "The Constellation that Returned from Hell",
    "The Tutorial is Too Hard",
    "Return of the Frozen Player",
    "Player Who Can't Level Up",
    "Level 1 Player",
    "Heavenly Demon Instructor",
    "Starting Today, I'm a Player",
    "Solo Leveling",
    "Tomb Raider King",
    "Solo Spell Caster",
    "I'm The Only One Loved by the Constellations!",
    "I Am The Sorcerer King",
    "SSS-Class Suicide Hunter",
    "Tower of God",
    "The First Hunter",
    "Raid",
    "Limitless Abyss",
    "Troll Trap",
    "I Became a Top Actor Just by Reading Books",
    "Debut or Die",
    "Top Star's Talent Ability",
    "The Definition of a Top Star",
    "My Superstar Uncle",
    "Once Again Idol",
    "Holy Idol",
    "Second Life Producer",
    "King of Drama",
    "Where Are You Looking, Manager?",
    "1st Year Max Level Manager",
    "My Daughter is a Music Genius",
    "Movies are Real",
    "Existence",
    "Villain To Kill",
    "Regressor Instruction Manual",
    "Pure Villain",
    "FFF-Class Trash Hero",
    "How to Live as a Villain",
    "The Earth Savior Selection",
    "Hero Has Returned",
    "Incompetent Villain",
    "I Grow Stronger By Eating!",
    "Death Row Boy",
    "Limitless Abyss",
    "Rooftop Sword Master",
    "My Daughter is a Dragon!",
    "Chronicles of the Martial God's Return",
    "My Daughter is the Final Boss",
    "I Become a Doting Father",
    "My Daughter is a Music Genius",
    "My Dad is Too Strong",
    "There was a Hero",
    "Spirit Farmer",
    "My Superstar Uncle",
    "Highschool Lunch Dad",
    "Manager Kim",
    "Peerless Dad",
    "I Stole the Number One Ranker's Soul",
    "Ending Maker",
    "Hero Killer",
    "Pure Villain",
    "Ashen Oreum",
    "Intoxicated Butterfly and Cold Moon",
    "Arachi: The First Irregular",
    "Aire",
    "Crimson Stone",
    "Dragon Ego",
    "Wanders of the Ruined",
    "Faust",
    "Hundred Years Game",
    "I Killed Him",
    "I'm the Martial Arts Villainess but I'm the Strongest!",
    "The Last Golden Child",
    "The Queens",
    "Kalsarin",
    "Virtual Reality Action RPG",
    "Knuckle Girl",
    "Pathfinder",
    "Zero Game",
    "Protect Me, Knight",
    "Goran",
    "The Warrior from the Golden Days",
    "Safe as Houses",
    "Tacit",
    "Uglyhood",
    "Delivery Knight",
    "Nano List",
    "Unholy Blood",
    "Crimson Karma",
    "Burning Effect",
    "Neolithic Girl",
    "Mrs. Angel",
    "Dangu",
    "I Don't Want This Kind of Hero",
    "Return of the SSS-Class Ranker",
    "Gaming Stream of the Genius",
    "I Have Max Level Luck",
    "Superhuman Battlefield",
    "Grim Reaper Online",
    "Hyper Luck",
    "Bug Hunter",
    "One-of-a-Kind Irregular",
    "Leveling Again: The Story of Agaya",
    "+99 Wooden Stick",
    "Sleeping Ranker",
    "Knight Under Heart",
    "The Healing Priest of the Sun",
    "Archmage Streamer",
    "Level Berserker",
    "Worn and Torn Newbie",
    "Ranker's Return (Remake)",
    "Final Boss",
    "Arcane Sniper",
    "Updater",
    "Ultra Alter",
    "Overgeared",
    "The Challenger",
    "The Legendary Moonlight Sculptor",
    "Please Have a Meal",
    "Taming Master",
    "Teenage Swordsman",
    "Leveling Up, Only By Eating!",
    "Virtual RPG",
    "Player",
    "Life Cry",
    "Undefeated Ranker",
    "Double Click",
    "The Strongest Florist",
    "I'm Destined for Greatness!",
    "Reader",
    "Ernak",
    "The God of "Game of God"",
    "Taebaek: The Tutorial Man",
    "Legend of Mir: Gold Armored Sword Dragon",
    "Arcana Fantasy",
    "Hardcore Leveling Warrior",
    "Old Newbie Kim ChunSik",
    "No Scope",
    "Dungein Athlete",
    "Reincarnation of the Veteran Soldier",
    "Newbie Management",
    "Magical Shooting: Sniper of Steel",
    "Transmigrating to the Otherworld Once More",
    "Surviving in an Action Manwha",
    "Worthless Regression",
    "Is this Hero for Real?",
    "The Road to Karma",
    "FFF-Class Trash Hero",
    "Dungeon Reset",
    "Deadbeat Hero",
    "Survival Story of a Sword King in a Fantasy World",
    "Seoul Station Druid",
    "Teenage Swordsman",
    "How to Live as a Villain",
    "The Live",
    "Wizard of Arsenia",
    "Androids Have no Blood",
    "New Life: Savior from Another World",
    "Hero has Returned",
    "Player",
    "Devil Sword King",
    "MookHyang - Dark Lady",
    "Her Summon",
    "The Greatest Estate Designer",
    "Treacherous Subject Saves the Country",
    "Solo Bug Player",
    "Return of the Mount Hua Sect",
    "Overgeared",
    "Dungeon Reset",
    "I Regressed as the Duke",
    "The Story of a Low-Rank Soldier Becoming a Monarch",
    "Max Level Returner",
    "Can I, a doctor, save 10 billion lives in another world?",
    "Level-Up Doctor",
    "To Hell with Being a Saint, I'm a Doctor",
    "Perfect Surgeon",
    "Physician Return",
    "I Reincarnated as the Legendary Surgeon",
    "Doctor's Rebirth",
    "Trauma Center",
    "Medical Return",
    "I'm The Only One with Genius DNA",
    "Genius Doctor Lee Moo-Jin",
    "Dr. Choi Tae-Soo",
    "A.I Doctor",
    "Doctor Elise",
    "Helmut: The Forsaken Child",
    "Standard of Reincarnation",
    "Can I, a doctor, save 10 billion lives in another world?",
    "Hero x Demon King x Villain",
    "The 10th Class Lout of the Knight Family",
    "Damn Reincarnation",
    "Newbie Management",
    "Overpowered Sword",
    "Academy's Undercover Professor",
    "To Hell with Being a Saint, I'm a Doctor",
    "Ending Maker",
    "Dukedom's Legendary Prodigy",
    "Swordmaster's Youngest Son",
    "I Regressed as the Duke",
    "Overbearing Tyrant",
    "The Lazy Swordmaster",
    "Transmigrating to the Otherworld Once More",
    "Return of the Unrivaled Spear Knight",
    "The Great Mage that Returned after 4000 Years",
    "The Max Level Hero has Returned!",
    "The Beginning After The End",
    "Talent-Swallowing Magician",
    "Reincarnation of the Suicidal Battle God",
    "The Dark Magician Transmigates after 66666 Years",
    "Legendary Youngest Son of the Marquis House",
    "Memorize",
    "Reformation of the Deadbeat Noble",
    "The Ember Knight",
    "The Greatest Estate Designer",
    "The Lord's Coins Aren't Decreasing?!",
    "The Story of a Low-Rank Soldier Becoming a Monarch",
    "Return of the 8th Class Magician",
    "A Returner's Magic Should be Special",
    "Ygret",
    "Duke Pendragon",
    "Solo Bug Player",
    "The Book of Lagier",
    "The Heavenly Demon Can't Live a Normal Life",
    "Wizard of Arsenia",
    "Skeleton Soldier Couldn't Protect the Dungeon",
    "Miracle Hero!",
    "The Rebirth of an 8th-Circled Mage",
    "Trash of the Count's Family",
    "Book Eating Magician",
    "Slave B",
    "Memorist",
    "Absolute Obedience",
    "Debut or Die",
    "King of the Mound",
    "Top Star's Talent Ability",
    "I Became a Genius Salesman",
    "Chemy",
    "System Rules",
    "Level-Up Doctor",
    "Perfect Surgeon",
    "The Definition of a Top Star",
    "My Superstar Uncle",
    "Big Life",
    "Rescue System",
    "Kitchen Soldier",
    "The Bastard of National Tax Service",
    "Youngest Chef from the 3rd Rate Hotel",
    "Quest Supremacy",
    "Reality Quest",
    "Movies are Real",
    "I'm The Only One with Genius DNA",
    "Where Are You Looking, Manager?",
    "Face Genius",
    "Cell",
    "Anon, I Know You!",
    "The Killer Detective",
    "A.I Doctor",
    "Lookism",
    "Genius Doctor Lee Moo-Jin",
    "I Stack Experience Through Reading Books",
    "1 Second",
    "Highschool Lunch Dad",
    "Success Story of the Omnipotent Soldier",
    "God of Cooking",
    "Face Slap",
    "The Boy of Death",
    "Champion's Path to Murim",
    "Death God",
    "Demonic Master of Mount Kunlun",
    "Youngest Son of the NamGung Clan",
    "I am Reborn as the Sword God",
    "Demon in Mount Hua",
    "Reincarnated Escort Warrior",
    "Reaper of the Drifting Moon",
    "Who Killed The Murim Lord?",
    "Heavenly Sword's Grand Saga",
    "Absolute Sword Sense",
    "Records of the Swordsman Scholar",
    "Sword Fanatic Wanders Through The Night",
    "Chronicles of the Martial God's Return",
    "The Star of a Supreme Ruler",
    "Return of the Mount Hua Sect",
    "Nano Machine",
    "Wandering Warrior of Wudang",
    "Volcanic Age",
    "The Return of the Crazy Demon",
    "I Reincarnated as the Crazed Heir",
    "Strongest Fighter",
    "Shinsu Jeil Sword",
    "The Strongest Ever",
    "Reincarnated War God",
    "Murim Login",
    "Tale of a Scribe Who Retires to the Countryside",
    "The Heavenly Demon Destroys the Lich King's Murim",
    "Lightning Degree",
    "The Chronicles of Heavenly Demon",
    "Legend of the Northern Blade",
    "Doctor's Rebirth",
    "Administrator Kang Jin Lee",
    "The World's Best Escort Bureau",
    "World's Best Assassin",
    "Storm Inn",
    "Enemies",
    "Androids Have No Blood",
    "Grand General",
    "Demon Spirit King",
    "Fist Demon of Mount Hua",
    "Heavenly Martial God",
    "Reincarnation of the Murim Clan's Former Ranker",
    "Star Instructor, Master Baek",
    "MookHyang - The Origin (Prequel)",
    "MookHyang - Dark Lady (Sequel)",
    "Bowblade Spirit",
    "Wind Spirit",
    "Yongbi",
    "Gosu",
    "Weak Teacher",
    "Heavenly Demon Cultivation Simulation",
    "Blade of Wind and Thunder",
    "King of Battlefield",
    "Gosam Mussang",
    "The Scholar's Reincarnation",
    "The Greatest in the World",
    "The Great Master Sunyoo",
    "King of Fire Dragon",
    "Life and Death: The Awakening",
    "The Millenium Alchemist",
    "Martial Artist Lee Gwak",
    "Return of the Bachelor",
    "Warrior Guard",
    "Past Lives of the Thunder God",
    "Escort Warrior",
    "The Senior Disciple",
    "The Scholar Warrior",
    "Memoir of the King of War",
    "Reign",
    "An Ha Muin",
    "Strong Representative",
    "Heavenly Moon",
    "Record of the War God",
    "Way to Heaven",
    "Sword Sheath's Child",
    "Reverse Villain",
    "Immortal, Invincible",
    "Strong Gale, Mad Dragon",
    "Legend of Asura - The Venom Dragon",
    "Infinite Level Up in Murim",
    "Severed Head",
    "Red Storm",
    "Mujang",
    "The History of Three States",
    "Marchen - The Embodiment of Tales",
    "Wolhan Gangcheonrok",
    "The Sword of Glory",
    "Wizard's Martial World",
    "Peerless Dad",
    "Revenge of Young Master Paeng",
    "The Breaker",
    "The Breaker: New Waves",
    "The Breaker: Eternal Force",
    "Dukedom's Legendary Prodigy",
    "The Dark Magician Transmigates after 66666 Years",
    "Kill The Hero",
    "The Healing Priest of the Sun",
    "Seoul Station Necromancer",
    "Solo Necromancy",
    "Second Life Ranker",
    "Reincarnation of the Murim Clan's Former Ranker",
    "SSS-Class Suicide Hunter",
    "Solo Leveling",
    "Records of the Swordsman Scholar",
    "Worthless Regression",
    "Doctor's Rebirth",
    "Overgeared",
    "Updater",
    "The Healing Priest of the Sun",
    "I Reincarnated as the Legendary Surgeon",
    "The Greatest Estate Designer",
    "Regressor Instruction Manual",
    "A Returner's Magic Should be Special",
    "The S-Classes that I Raised",
    "The Ember Knight",
    "Tale of a Scribe Who Retires to the Countryside",
    "Please Have a Meal",
    "Physician Return",
    "Dungeon Reset",
    "Estio",
    "Leveling Up, By Only Eating!",
    "The Legendary Moonlight Sculptor",
    "Miracle Hero!",
    "King of Fire Dragon",
    "Double Click",
    "Return of the Bachelor",
    "Trash of the Count's Family",
    "The Strongest Florist",
    "I'm Destined for Greatness!",
    "Book Eating Magician",
    "Marchen - The Embodiment of Tales",
    "Omniscient Reader's Viewpoint",
    "Dungeon Reset",
    "There was a Hero",
    "Psychopath Hero",
    "Grim Reaper Online",
    "Androids Have no Blood",
    "Skeleton Soldier Couldn't Protect the Dungeon",
    "Call of the Spear",
    "Is There a Problem if the Demon King is a Goblin?!",
    "Lord of Goblins",
    "Legend of Mir: Gold Armored Sword Dragon",
    "The Dungeon Master",
    "Brainless Witch",
    "Dragon Ego",
    "Ice Jade",
    "Olgami",
    "Our Classmate Sookgyung",
    "Uglyhood",
    "Transfer Student Oh-Deokgu",
    "Noblesse",
    "Unholy Blood",
    "Nano List",
    "Asura",
    "Blast",
    "Papi Nyang",
    "Phantom",
    "Her Hero",
    "Wake Up Deadman",
    "Under PRIN",
    "Watch Dog",
    "Overgeared",
    "Ranker's Return (Remake)",
    "Leveling With The Gods",
    "Reformation of the Deadbeat Noble",
    "SSS-Class Suicide Hunter",
    "Overpowered Sword",
    "The Beginning After The End",
    "Solo Max-Level Newbie",
    "Villain To Kill",
    "The S-Classes that I Raised",
    "Swordmaster's Youngest Son",
    "Absolute Sword Sense",
    "King of the Mound",
    "Talent-Swallowing Magician",
    "Duke Pendragon",
    "Second Life Ranker",
    "Return of the Disaster-Class Hero",
    "Big Life",
    "The Story of a Low-Rank Soldier Becoming a Monarch",
    "My Dad is Too Strong",
    "Ygret",
    "The Newbie is Too Strong",
    "Is this Hunter for Real?",
    "The Lord's Coins Aren't Decreasing",
    "The Max Level Hero has Returned!",
    "Standard of Reincarnation",
    "Please Have a Meal",
    "+99 Wooden Stick",
    "Trash of the Count's Family",
    "Street Restaurant of a Returned Hero",
    "Treacherous Subject Saves the Country",
    "The Dark Magician Transmigrates After 66666 Years",
    "Max Level Returner",
    "Return of the Frozen Player",
    "The Definition of a Top Star",
    "Gangnam Dokkaebi",
    "Cursed Manager's Regression",
    "Final Boss",
    "Spirit Farmer",
    "Eleceed",
    "Tomb Raider King",
    "Leveling Up with Likes",
    "Archmage Streamer",
    "Dungeon Reset",
    "Taming Master",
    "Estio",
    "I'm Destined for Greatness!",
    "Solo Login",
    "Dracorun",
    "Heavenly Master",
    "Bowblade Spirit",
    "Midwood",
    "I Became a Top Actor Just by Reading Books",
    "Youngest Son of the NamGung Clan",
    "Cursed Manager’s Regression",
    "Return of the SSS-Class Ranker",
    "Debut or Die",
    "Clever Cleaning Life of the Returned Genius Hunter",
    "Heavenly Sword's Grand Saga",
    "I Became a Renowned Family's Sword Prodigy",
    "Absolute Sword Sense",
    "I Obtained a Mythic Item",
    "Swordmaster's Youngest Son",
    "I Regressed as the Duke",
    "My Daughter is the Final Boss",
    "Treacherous Subject Saves the Country",
    "Heavenly Demon Bakery",
    "Worthless Regression",
    "Legendary Youngest Son of the Marquis House",
    "Physician Return",
    "Rescue System",
    "The Hero Returns",
    "Leveling with the Gods",
    "Volcanic Age",
    "Worn and Torn Newbie",
    "Return Survival",
    "The Story of a Low-Rank Soldier Becoming a Monarch",
    "The S-Classes that I Raised",
    "Return to Player",
    "Kill The Hero",
    "Memorize",
    "Reincarnation of the Suicidal Battle God",
    "The Return of the Crazy Demon",
    "The Lord's Coins Aren't Decreasing?!",
    "Return of the Shattered Constellation",
    "Chronicles of Heavenly Demon",
    "Return of the Unrivaled Spear Knight",
    "Return of the 8th Class Magician",
    "A Returner's Magic Should be Special",
    "Starting Today, I'm a Player",
    "Once Again Idol",
    "Tomb Raider King",
    "Skeleton Soldier Couldn't Protect the Dungeon",
    "Return of the Legend",
    "Second Life Producer",
    "SSS-Class Suicide Hunter",
    "Real Man",
    "My Daughter is a Music Genius",
    "King of Drama",
    "FFF-Class Trashero",
    "The Golden Age",
    "This is the Law",
    "The God of Pro Wrestling",
    "Immortal, Invincible",
    "History of Three States",
    "Infinite Level Up in Murim",
    "Past Life Regressor",
    "Reincarnated War God",
    "Second Life of a Gangster",
    "Medical Return",
    "Again My Life",
    "Champion's Path to Murim",
    "Demonic Master of Mount Kunlun",
    "Standard of Reincarnation",
    "Can I, a doctor, save 10 billion lives in another world?",
    "Debut or Die",
    "I am Possessed by the Sword God",
    "Reincarnated Escort Warrior",
    "The 10th Class Lout of the Knight Family",
    "Damn Reincarnation",
    "Academy's Undercover Professor",
    "To Hell with Being a Saint, I'm a Doctor",
    "Ending Maker",
    "Reincarnated as a Fish",
    "Dukedom's Legendary Prodigy",
    "I Regressed as the Duke",
    "Overbearing Tyrant",
    "The Lazy Swordmaster",
    "Heavenly Demon Bakery",
    "My Civil Servant Life Reborn in the Strange World",
    "Wandering Warrior of Wudang",
    "The Beginning after the End",
    "I Reincarnated as the Legendary Surgeon",
    "Return of the Mount Hua Sect",
    "Duke Pendragon",
    "I Reincarnated as the Crazed Heir",
    "Strongest Fighter",
    "The Dark Magician Transmigates after 66666 Years",
    "Villain to Kill",
    "The Heavenly Demon Destroys the Lich King's Murim",
    "Ygret",
    "The Greatest Estate Designer",
    "The Great Mage that Returned after 4000 Years",
    "Chronicles of Heavenly Demon",
    "Solo Bug Player",
    "Doctor's Rebirth",
    "The Book of Lagier",
    "The Heavenly Demon Can't Live a Normal Life",
    "Heavenly Martial God",
    "I'm the Only One Loved by the Constellations!",
    "Ha Buk Paeng's Youngest Son",
    "The Rebirth of an 8th-Circled Mage",
    "God of Blackfield",
    "Reincarnation of the Murim Clan's Former Ranker",
    "The Scholar's Reincarnation",
    "Good Luck, Hero!",
    "Past Lives of the Thunder God",
    "Trash of the Count's Family",
    "Immortal, Invincible",
    "Call of the Spear",
    "Lord of Goblins",
    "Trapped in a Webnovel as a Good-for-Nothing",
    "The Dungeon Master",
    "Wizard's Martial World",
    "From the Grave and Back",
    "Reincarnated War God",
    "I Shall Live as a Prince",
    "Reverse Villain",
    "Player Who Returned 10,000 Years Later",
    "Chronicles of the Martial God's Return",
    "The Constellation that Returned from Hell",
    "My Dad is Too Strong",
    "Seoul Station Necromancer",
    "Seoul Station Druid",
    "Street Restaurant of a Returned Hero",
    "Hero Has Returned",
    "Max Level Returner",
    "Maxed Out Leveling",
    "Heavenly Demon Bakery",
    "Death God",
    "Return of the SSS-Class Ranker",
    "I Became a Renowned Family's Sword Prodigy",
    "Dukedom's Legendary Prodigy",
    "Legendary Youngest Son of the Marquis House",
    "Hero Has Returned",
    "Nano Machine",
    "Return of the Disaster-Class Hero",
    "Return of the Mount Hua Sect",
    "The Dark Magician Transmigrates after 66666 Years",
    "Second Life Ranker",
    "Kill the Hero",
    "Psycho Revenge",
    "Reincarnation of the Suicidal Battle God",
    "Return of the Shattered Constellation",
    "The Great Mage that Returned after 4000 Years",
    "Chronicles of Heavenly Demon",
    "Legend of the Northern Blade",
    "Return of the Unrivaled Spear Knight",
    "Guard Pass",
    "Royal Path",
    "Dungeon & Artifacts",
    "The Rebirth of an 8th-Circled Mage",
    "Burnout Shock",
    "Trigger",
    "Fray",
    "Goran",
    "Past Lives of the Thunder God",
    "Legend of Asura - The Venom Dragon",
    "The Ember Knight",
    "Ha Buk Paeng's Youngest Son",
    "Limitless Abyss",
    "Reincarnated War God",
    "Rooftop Swordmaster",
    "The Greatest Outcast",
    "The 18 Year Old Spy",
    "Hectopascal",
    "Absolute Obedience",
    "The Bully In-Charge",
    "Switch",
    "Mercenary Enrollment",
    "True Education",
    "How To Fight",
    "Study Group",
    "Ganzi Monster",
    "Quest Supremacy",
    "Reality Quest",
    "Guard Pass",
    "God of Blackfield",
    "Ssam Bbak",
    "Anon, I Know You!",
    "Boss In School",
    "Trigger",
    "Weak Hero",
    "Psycho Revenge",
    "Highschool Lunch Dad",
    "This World is Money and Power",
    "Show me the Lucky-Boss!",
    "Beyond the Strong",
    "Mabaram The School Conqueror",
    "Lookism",
    "King of Piling",
    "Gang of School",
    "Dog Fight Club",
    "Wind Breaker",
    "Plaza",
    "Second Life of a Gangster",
    "The Villain",
    "The Greatest Outcast",
    "Ultimate Legend - Kang Hae Hyo",
    "I Became the Tyrant of a Defense Game",
    "I am Reborn as the Sword God",
    "I Have Max Level Luck",
    "The Novel's Extra (Remake)",
    "Surviving in an Action Manwha",
    "The Greatest Estate Designer",
    "Doctor's Rebirth",
    "Regressor Instruction Manual",
    "Trash of the Count's Family",
    "Trapped in a Webnovel as a Good-for-Nothing",
    "Omniscient Reader's Viewpoint",
    "King of the Mound",
    "Infinity",
    "Build Up",
    "The Extreme",
    "Winning Shot",
    "XTen",
    "Wind Breaker",
    "The Boxer",
    "My School Life Pretending to be a Worthless Person",
    "I Have Max Level Luck",
    "Academy's Undercover Professor",
    "The Novel's Extra (Remake)",
    "Transcension Academy",
    "I Obtained a Mythic Item",
    "Overpowered Sword",
    "Kill The Dragon",
    "Legendary Youngest Son of the Marquis House",
    "Talent-Swallowing Magician",
    "Return of the Unrivaled Spear Knight",
    "The Great Mage that Returned after 4000 Years",
    "The Heavenly Demon Destroys the Lich King's Murim",
    "The Ember Knight",
    "Eleceed",
    "The Lord's Coins Aren't Decreasing?!",
    "The Beginning After the End",
    "Reformation of the Deadbeat Noble",
    "Jungle Juice",
    "Nano Machine",
    "Lightning Degree",
    "Ygret",
    "The Book Eating Magician",
    "A Returner's Magic Should be Special",
    "Shaman",
    "Slave B",
    "Helmut: The Forsaken Child",
    "Player Who Returned 10,000 Years Later",
    "Demon in Mount Hua",
    "Reaper of the Drifting Moon",
    "I Have Max Level Luck",
    "Raising Newbie Heroes in Another World",
    "The World after the Fall",
    "Return of the Disaster-Class Hero",
    "Limit Breaker",
    "Seoul Station Druid",
    "Hoarding in Hell",
    "Maxed Out Leveling",
    "FFF-Class Trash Hero",
    "The Tutorial Tower of the Advanced Player",
    "The Max Level Hero has Returned!",
    "The Constellation that Returned from Hell",
    "Survival Story of the Sword King in a Fantasy World",
    "The Millenium Alchemist",
    "Fist Demon of Mount Hua",
    "Return of the Bachelor",
    "I Became a Tyrant of a Defense Game",
    "I am Reborn as the Sword God",
    "King of the Mound",
    "Transcension Academy",
    "Clever Cleaning Life of the Returned Genius Hunter",
    "The Novel's Extra (Remake)",
    "I Became a Renowned Family's Sword Prodigy",
    "I Obtained a Mythic Item",
    "Level-Up Doctor",
    "Perfect Surgeon",
    "Rescue System",
    "Kitchen Soldier",
    "I Reincarnated as a Legendary Surgeon",
    "Return of the Shattered Constellation",
    "I Have an SSS-rank Trait, But I want a Normal Life",
    "Archmage Streamer",
    "Nano Machine",
    "SSS-Class Suicide Hunter",
    "Limit Breaker",
    "My Superstar Uncle",
    "The S-Classes that I Raised",
    "The Max Level Hero has Returned!",
    "Murim Login",
    "Regressor Instruction Manual",
    "FFF-Class Trash Hero",
    "Memorize",
    "The Lord's Coins Aren't Decreasing?!",
    "The Greatest Estate Designer",
    "Solo Bug Player",
    "Quest Supremacy",
    "Reality Quest",
    "I'm The Only One with Genius DNA",
    "All Rounder",
    "Reincarnation of the Murim Clan's Former Ranker",
    "Heavenly Demon Cultivation Simulation",
    "Success Story of the Omnipotent Soldier",
    "Face Genius",
    "King of Drama",
    "A.I Doctor",
    "God of Cooking",
    "The Second Coming of Gluttony",
    "Omniscient Reader's Viewpoint",
    "Solo Leveling",
    "Auto Hunting",
    "All Rounder",
    "Dead Life",
    "Psychopath Hero",
    "Parallel City",
    "Return Survival",
    "Safe as Houses",
    "Tacit",
    "Undead",
    "Zombie Fight",
    "Dead Days",
    "My Daughter is a Zombie",
    "Dreamcide",
    "Zombie Ship"
];
let currentIndex = 0;
const manhwas = ['SSS Revival Hunter', 'Solo Leveling', 'The Beginning After the End'];
const savedManhwasKey = 'savedManhwas';

// Fetch manhwa data from API
async function fetchManhwaInfo(manhwaName) {
    try {
        const response = await fetch(`https://api.jikan.moe/v4/manga?q=${encodeURIComponent(manhwaName)}`);
        const data = await response.json();
        const manhwa = data.data[0]; // Assuming the first result is the desired manhwa

        const manhwaData = {
            title: manhwa.title,
            coverImage: manhwa.images.jpg.image_url,
            chapterCount: manhwa.chapters
        };

        displayManhwaInfo(manhwaData);
    } catch (error) {
        console.error('Error fetching manhwa data:', error);
    }
}

// Display fetched manhwa info
function displayManhwaInfo(data) {
    document.getElementById('coverImage').src = data.coverImage;
    document.getElementById('title').innerText = `Title: ${data.title}`;
    document.getElementById('chapterCount').innerText = `Number of Chapters: ${data.chapterCount}`;
}

// Save current manhwa to cookies
function saveToCookies(manhwa) {
    let cookieManhwas = JSON.parse(getCookie(savedManhwasKey) || "[]");
    cookieManhwas.push(manhwa);
    document.cookie = `${savedManhwasKey}=${JSON.stringify(cookieManhwas)};path=/`;
}

// Get cookie by name
function getCookie(name) {
    const value = `; ${document.cookie}`;
    const parts = value.split(`; ${name}=`);
    if (parts.length === 2) {
        return parts.pop().split(';').shift();
    }
}

// Display saved manhwas from cookies
function displaySavedManhwas() {
    const saved = JSON.parse(getCookie(savedManhwasKey) || "[]");
    alert("Saved Manhwas:\n" + saved.join('\n'));
}

// Swipe event handling
let touchstartX = 0;
let touchendX = 0;

function checkSwipe() {
    if (touchendX < touchstartX) {
        saveToCookies(manhwas[currentIndex]);
        currentIndex = (currentIndex + 1) % manhwas.length;
        fetchManhwaInfo(manhwas[currentIndex]);
    }

    if (touchendX > touchstartX) {
        currentIndex = (currentIndex + 1) % manhwas.length;
        fetchManhwaInfo(manhwas[currentIndex]);
    }
}

document.getElementById('coverImage').addEventListener('touchstart', e => {
    touchstartX = e.changedTouches[0].screenX;
});

document.getElementById('coverImage').addEventListener('touchend', e => {
    touchendX = e.changedTouches[0].screenX;
    checkSwipe();
});

document.getElementById('viewSavedBtn').addEventListener('click', displaySavedManhwas);

// Initial fetch
fetchManhwaInfo(manhwas[currentIndex]);
